### PR TITLE
Translate module Licensing

### PR DESCRIPTION
**Pull request by Cesarfr**
* This patches adds selectable languages to the Licensing module.
* Fixed stylesheets.
* All visible strings in the files PHP were translated also the strings JavaScript.
* Changed charset 'latin1' to 'utf8' in the database to future news languages.
* All updates are merged in this repository to add the new features.
* Added script to change the database charset to utf8 in an existing installation.

You can change the language of the interfaces dynamically thanks to the dropdown added in all interfaces, in this update English is the language by default, but you can change the language to French if you prefer.
This dropdown is located in the right of the screen, next to the dropdown to change the module:

selection_013

## Screenshots
This module should look as follows:

### Home
**English**
lic_home-en

**French**
lic_home-fr

### New License
**English**
lic_newlic-en

**French**
lic_newlic-fr

### Licenses in progress
**English**
lic_licinp-en

**French**
lic_liinp-fr

### Expression comparision
**English**
lic_exp-en
**French**
lic_exp-fr

### JavaScript:
**English**
js_en

**French**
js_fr

To know more about what translation and internationalization are and how they work, see this page on the wiki: [Translation of ERMS CORAL](https://github.com/ndlibersa/CORAL-Main/wiki/Translation-of-ERMS-CORAL).

### CODE REVIEW

**Comment by remocrevo** [comment]
Do you expect that users will need to change between languages frequently? I would think most users only need to choose their language one time, so it seems strange for the language selector to be so prominent on every page. Is this necessary?

**Comment by Cesarfr** [comment]
Hello @remocrevo , 
The main purpose is to bring to the user the possibility of change the language when he wants.
I think it is necessary because if the user does not understand completely the language for default, but he has notions of another language he can change this without problem, but if the language is chosen once time, the user must return to the point where he has chosen the language, change the language and return to the page where he work. This is complicated.

Sorry for my bad English.

**Comment by coraladmin** [comment]
So does the language selection only show in the top right corner of the main tabs, so Home, Calendar, Admin, etc? It does not show separately in some of the pop-up windows such as the Add New screens, is that correct? I agree with Remington that this doesn't really need to be everywhere. Having it on the Home page only would seem sufficient to me unless it is just easier to embed on every page. 

One point though as we look to the future. We are putting a lot in the main tab line of the page header. If we add much more we are going to run out of room. Not something we probably need to deal with now but in the future things like the Change Module and Language feature may need to be moved somewhere else entirely.

**Comment by Cesarfr** [comment]
Hello @coraladmin , you are the reason, the language selection is shown only in the main tabs. I think we can move the language selector to the `footer` to avoid overload the `header`.

About of the selector, I think is important in all tab of the module but if you want we can show this in the `Home` page only one time.

I put this in all tabs because I applied the `usability` in all modules and I think is important give to the user the possibility to change the language when he wants.

Thanks.

**Comment by benheet** [comment]
Anyone else want to comment on where the translate feature should show up? Anyone feel strongly one way or another?

**Comment by PaulPoulain** [comment]
Ben I hope no one will, because that would mean updating all modules, and Cesar has ended his internship. He liked what he did, so is continuing a little bit outside from the intern, but he will not do that for years ;-)
(I hope I'll be able to test & update translation of other modules in july. june has been crazy !)

**Comment by jeffnm** [comment]
Header or footer are both acceptable to me.

**Comment by remocrevo** [comment]
@PaulPoulain Could you rebase this branch now that I've merged two other pull requests? And I'm concerned about the possible error if a server is missing the gettext PHP extension (mentioned in Auth module pull request 3), since it would require changes to the server configuration. I know you couldn't reproduce the error, but I would rather be safe and have the code check for the PHP extension. We should also mention this requirement in the install/upgrade instructions for all translated modules.

**Comment by remocrevo** [comment]
@PaulPoulain I merged in the form validation pull request. Please note that it added some error text, usually with the pattern "Error - Please enter ...", which need to be translated.

**Comment by clrh** [comment]
I asked permissions to push on Cesar repository and try a first rebase you can see here: https://github.com/clrh/licensing/tree/translate-licensing-rebase

At the moment, I see the translation and see no problem but continuing tests.

**Comment by clrh** [comment]
Rebased and pushed on the right repository, ready for testing again ;)

**Comment by remocrevo** [comment]
Minor question: When you (BibLibre) chose to use Gettext.js, did you consider other options? That choice seems stable, but also not maintained any more. It looks like the official GNU Gettext project now supports Javascript. Should we consider using that instead? This is probably a minor issue, but I thought it was worth asking.

**Comment by veggiematts** [comment]
We chose Gettext.js because it was the only tool we found allowing to store the strings outside of the code, in .po files.

The use of .po files seemed very relevant to us, as it allows non-developpers to work on translations, with dedicated graphical tools, like Poedit.

Could you please provide a link about Gnu gettext itself supporting javascript ?

**Comment by remocrevo** [comment]
@veggiematts Here is a link to the news announcement from 2013: 
http://savannah.gnu.org/forum/forum.php?forum_id=7641

And here are the technical specs:
https://www.gnu.org/software/gettext/manual/gettext.html#JavaScript

As I mentioned, this is probably a minor issue, so if you think it is not worth changing at this point, we can proceed with Gettext.js.

**Comment by veggiematts** [comment]
Please someone correct me if I'm wrong here.

From my point of view, Gnu gettext support of javascript is about extracting the strings from the source code, in order to create po files.

Those files can then be translated to several languages.

But then, we still need a Javascript library that will load the strings at run-time. That's what Gettext.js does.

**Comment by remocrevo** [comment]
It looks like the new error messages still need to be made translatable (examples: "Error - Please..." in js/admin.js).  But that can easily be done as a separate issue.

**Comment by coraladmin** [comment]
Le 12/10/2015 15:06, remocrevo a écrit :
>
> It looks like the new error messages still need to be made 
> translatable (examples: "Error - Please..." in js/admin.js). But that 
> can easily be done as a separate issue.
>
I agree. And it will probably be a new entry on coding guidelines for 
future patches : how do we want to handle new strings / strings updates ?

(probably a topic for a future steering committee discussion

-- 
Paul Poulain, Associé-gérant / co-owner
BibLibre, Services en logiciels libres pour les bibliothèques
BibLibre, Open Source software and services for libraries

**Comment by remocrevo** [comment]
Also, note that this commit added the Gettext.js package to the CORAL code. Since it is a small, stable project with no current development, I think it is fine to package it with CORAL. In general, however, I think external projects should be kept separate from CORAL and handled as part of the install/update process.

**Pull request merged**
